extension: add a --without-x to mozjs recipes to prevent a cross_compile badness which lead to a break
Without this patch we get in do_configure the failure because we search
for librarypathes in configure to detect -lICE and found it in /usr/lib
(which is not good in a cross_compile environemtn)

ERROR: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.
Rerun configure task after fixing this. The path was '/development/openembedded/development/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/mozjs/17.0.0-r0/mozjs17.0.0/js/src'
ERROR: Function failed: do_qa_configure

The failure comes from meta/classes/insane.bbclass:875.

Signed-off-by: Silvio F <silvio.fricke@gmail.com>